### ISSUE TITLE
the instance url textbox needs to normalize its input to make login less error-prone

### ISSUE THREAD

**Issue by vivlim** [vivlim/pillbug#10]
currently there are at least two ways to fail logging into pillbug that I know of:
- omitting url scheme
- a trailing slash at the end of the instance domain

both of these cause an unhelpful error to be shown. i papered over the first one with a warning that says https:// is needed, the trailing slash could be papered over similarly in the short term but it'd be much better to normalize the input and make some inferences about it (like if a scheme is missing it's probably https)

**Comment by ChaiaEran** [comment]
I can take a look at this one if you'd like.

**Comment by ChaiaEran** [comment]
I made a fork since I don't have contribution perms, [check it out](https://github.com/ChaiaEran/pillbug/tree/login-sanitization)

**Comment by vivlim** [comment]
that'd be awesome, feel free to tag me here or in zulip if you have questions

**Comment by vivlim** [comment]
you can go ahead and open a pr from your fork, I'll review the change there. also I'm not sure if my setup will build and deploy from a fork or and I'm curious

**Comment by vivlim** [comment]
fixed by @ChaiaEran in #12!
