### ISSUE TITLE
posts are sometimes comically tall on the post page

### ISSUE THREAD

**Issue by lunasorcery** [vivlim/pillbug#36]
for example:

<img width="1800" alt="Screenshot 2024-10-09 at 21 13 52" src="https://github.com/user-attachments/assets/6c5a0ab0-8318-411d-ad3d-673736771f27">

From seeing this a few times it looks like it's stretching to make the right-hand side of the page match the height of the user bio on the left. I've noticed from some local testing that dropping the `flex-auto` from here seems to fix it:

https://github.com/vivlim/pillbug/blob/13a3b80af6e3a6975cc22e221b3f56ceb057e23e/src/components/post/index.tsx#L213

...but I don't know flexbox even remotely well enough to know if that's the 'correct' fix.

**Comment by vivlim** [comment]
@snowkat what do you think?

personally i'm fine with taking the change to remove flex-auto regardless of its correctness, assuming it works on desktop and mobile fine. (i have not spent any time thinking about whether it's correct)

**Comment by snowkat** [comment]
Looks good to me!

Seems like `flex-auto` was added to replace `flex-1`, but posts shouldn't need to shrink/grow based on other elements. So at best it's not doing much, and at worst... well, this.
