### ISSUE TITLE
avatars to the side of posts have an oversized hitbox

### ISSUE THREAD

**Issue by lunasorcery** [vivlim/pillbug#37]
As shown, clicking anywhere in the highlighted region links to the user's profile.
<img width="211" alt="Screenshot 2024-10-09 at 22 24 39" src="https://github.com/user-attachments/assets/08cfb532-479c-4c3d-8f2c-4ae34213d672">

`<AvatarImage>` and `<AvatarLink>` possibly want restructuring? `<AvatarLink>` wraps an `<a>` around an `<AvatarImage>`, but inherits its own size from the parent element, causing the above.

**Comment by JTrunov** [comment]
Hello! I would like to give it a try.
