### ISSUE TITLE
getting 404s when trying to view posts that shouldn't be 404s.

### ISSUE THREAD

**Issue by vivlim** [vivlim/pillbug#60]
fairly often after the multiaccount update, i'll try to view a post and get a 404.

**Comment by rspeer** [comment]
I've probably just encountered an example of it:

URL: https://pillbug.vivl.im/post/01JAQ9CKHR172ENHZDMEHCXNA3

Result:

> Request failed with status code 404
> H@https://pillbug.vivl.im/assets/auth-manager-HcGzxvZb.js:1:19288
> ei@https://pillbug.vivl.im/assets/auth-manager-HcGzxvZb.js:3:1030
> q@https://pillbug.vivl.im/assets/auth-manager-HcGzxvZb.js:3:6058

**Comment by vivlim** [comment]
figured this out - the api returns a 404 when trying to get thread context of a reblog, so the right thing to do in that case is to fetch thread context for the *reblogged* post instead. fixed this in https://github.com/vivlim/pillbug/commit/c8e3a7cd516abebf94a01ad9fae37289efe809ab
