### ISSUE TITLE
Pillbug doesn't render some Markdown in posts

### ISSUE THREAD

**Issue by ChaiaEran** [vivlim/pillbug#69]
Pillbug posts seem to just completely ignore some Markdown formatting. The three images listed are:

- The raw Markdown in the Pillbug editor.
- The post in Pillbug's rendering.
- The post in Phanpy's rendering.

![image](https://github.com/user-attachments/assets/0857584e-fcd8-4f5d-b2a2-0b7771790d6a)
![image](https://github.com/user-attachments/assets/db66443f-3fe5-4386-a37b-a2018a80fc54)
![image](https://github.com/user-attachments/assets/1ee1f11a-94d1-4c54-91c9-7e9bca23c25e)

**Comment by ChaiaEran** [comment]
Also checked for completeness' sake; it doesn't work with HTML tags either.

**Comment by vivlim** [comment]
This is on gotosocial, right? Could you please write the same post in phanpy and see how it appears in pillbug? I want to see if phanpy transforms the html before sending it to gts or not.

I'm also curious if the results end up any different on akkoma.

**Comment by ChaiaEran** [comment]
![image](https://github.com/user-attachments/assets/d2900288-a58b-4aaa-b6c6-ead3c3247e38)
![image](https://github.com/user-attachments/assets/d9a737ec-27cd-45bb-a0fb-bc64a47c683b)
![image](https://github.com/user-attachments/assets/54d7b0c3-52aa-4b86-bf43-077258dd4f25)

Looks like the problem is squarely in pillbug's rendering of posts, not in anything on the GtS backend.

**Comment by vivlim** [comment]
pillbug doesn't actually do any markdown parsing at the moment, it just sanitizes the html that the backend sends and sticks it in an element. I'll need to dump the markup that the backend sends for that post to see what I'm working with

**Comment by vivlim** [comment]
oh it could also be possible that some styles I'm pulling in are being overridden. for example when I use a h1 element in a component, it looks like regular text

**Comment by vivlim** [comment]
OK, yeah, just missing some css. in the inspector the post looks like this

![image](https://github.com/user-attachments/assets/896ea512-5713-4946-8cf7-dc082613beea)

these need to have styles applied to them when they're inside a `.post-content`

**Comment by vivlim** [comment]
I think I've done all of these except blockquotes now.
