### ISSUE TITLE
Pillbug eats links on newlines

### ISSUE THREAD

**Issue by ChaiaEran** [vivlim/pillbug#90]
I'm presuming this is a side effect of post stitching? Phanpy screenshot included for comparison.

![image](https://github.com/user-attachments/assets/1710b4ac-ca86-4ad8-baff-f32d7c107fc5)
![image](https://github.com/user-attachments/assets/8be30390-50b5-489a-a591-92ba1fbcaad3)

**Comment by vivlim** [comment]
that's strange, might be a side effect of a html rendering change I made lately (instead of setting innerhtml after parsing I instead transform it into jsx elements so I have a way to rewrite and add extra functionality to certain elements)
thanks for the report!

**Comment by vivlim** [comment]
should be fixed by https://github.com/vivlim/pillbug/commit/26f3bec489af4c4ae99998ce7a04d06b1ffbad62
